# Generated by Django 5.1.1 on 2024-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookaro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
